name: ClimateEvents
version: '0.3-BETA'
main: org.rexi.climateEvents.ClimateEvents
api-version: '1.21'
author: Rexi666
commands:
  climateevents:
    description: Comando principal para eventos climáticos.
    aliases: [ce]
    subcommands:
      acidrain:
        description: Controla el evento de lluvia ácida.
      solarflare:
        description: Controla el evento de llamarada solar.
      electricstorm:
        description: Contola el evento de tormenta eléctrica
permissions:
  climateevents.admin:
    description: Permite usar los comandos de admin
    default: op
  climateevents.admin.events:
    description: Permite usar los comandos eventos
    default: op